extends: cheminfo
parserOptions:
  sourceType: module
rules:
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: all
      allow: []
  no-await-in-loop:
    - warn
  max-lines-per-function:
    - warn
    - max: 1000
      skipBlankLines: true
      skipComments: true
  no-undefined:
    - warn
overrides:
  - files: '**/__tests__/**'
    rules:
      max-lines-per-function:
        - off
env:
  jest: true
  node: true
