root: true
workspaces: true
reject:
  # https://github.com/cheminfo/eslint-config/issues/49
  - eslint
  # https://github.com/cheminfo/mass-tools/issues/192
  - ml-fcnnls
  # https://github.com/cheminfo/mass-tools/issues/193
  - svgdom
  # https://github.com/cheminfo/mass-tools/issues/191
  - '@orama/orama'